### ISSUE TITLE
Wrong css syntax

### ISSUE THREAD

**Issue by kratosvn** [technext/tournest#1]
Hi there,
I see a syntax in bootsnav.css in line 1283.  it should be  !important not " !mportant"
Pls consider to fix it.
`
 nav.navbar.bootsnav .megamenu-content.tabbed{
        padding-left: 0 !mportant;
    }
`

**Comment by anindya-dhruba** [comment]
Hello there.
Thank you for reporting the bug.

We will fix it in the next update.

Thanks again.
